2025-03-01 16:35:37,811 INFO    MainThread:11728 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2025-03-01 16:35:37,811 INFO    MainThread:11728 [wandb_setup.py:_flush():79] Configure stats pid to 11728
2025-03-01 16:35:37,811 INFO    MainThread:11728 [wandb_setup.py:_flush():79] Loading settings from C:\Users\joalb\.config\wandb\settings
2025-03-01 16:35:37,811 INFO    MainThread:11728 [wandb_setup.py:_flush():79] Loading settings from D:\RLRL\CUCAI-Rocket-League-Agent\RL-Agent\wandb\settings
2025-03-01 16:35:37,811 INFO    MainThread:11728 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'mode': 'disabled'}
2025-03-01 16:35:37,811 INFO    MainThread:11728 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': 'online', '_disable_service': None}
2025-03-01 16:35:37,833 INFO    MainThread:11728 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'RL-Agent\\example.py', 'program_abspath': 'D:\\RLRL\\CUCAI-Rocket-League-Agent\\RL-Agent\\example.py', 'program': 'D:\\RLRL\\CUCAI-Rocket-League-Agent\\RL-Agent\\example.py'}
2025-03-01 16:35:37,833 INFO    MainThread:11728 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-03-01 16:35:37,833 INFO    MainThread:11728 [wandb_init.py:_log_setup():533] Logging user logs to D:\RLRL\CUCAI-Rocket-League-Agent\RL-Agent\wandb\run-20250301_163537-06vvbrlr\logs\debug.log
2025-03-01 16:35:37,834 INFO    MainThread:11728 [wandb_init.py:_log_setup():534] Logging internal logs to D:\RLRL\CUCAI-Rocket-League-Agent\RL-Agent\wandb\run-20250301_163537-06vvbrlr\logs\debug-internal.log
2025-03-01 16:35:37,834 INFO    MainThread:11728 [wandb_init.py:init():619] calling init triggers
2025-03-01 16:35:37,834 INFO    MainThread:11728 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'n_proc': 32, 'min_inference_size': 29, 'timestep_limit': 1e+16, 'exp_buffer_size': 150000, 'ts_per_iteration': 50000, 'standardize_returns': True, 'standardize_obs': False, 'policy_layer_sizes': [1024, 1024, 1024, 1024, 512], 'critic_layer_sizes': [2048, 1024, 1024, 1024, 512], 'ppo_epochs': 2, 'ppo_batch_size': 50000, 'ppo_minibatch_size': 50000, 'ppo_ent_coef': 0.001, 'ppo_clip_range': 0.2, 'gae_lambda': 0.95, 'gae_gamma': 0.99, 'policy_lr': 0.0002, 'critic_lr': 0.0002, 'shm_buffer_size': 8192}
2025-03-01 16:35:37,834 INFO    MainThread:11728 [wandb_init.py:init():669] starting backend
2025-03-01 16:35:37,834 INFO    MainThread:11728 [wandb_init.py:init():673] sending inform_init request
2025-03-01 16:35:37,838 INFO    MainThread:11728 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-03-01 16:35:37,838 INFO    MainThread:11728 [wandb_init.py:init():686] backend started and connected
2025-03-01 16:35:37,846 INFO    MainThread:11728 [wandb_init.py:init():781] updated telemetry
2025-03-01 16:35:37,903 INFO    MainThread:11728 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2025-03-01 16:35:38,183 ERROR   MainThread:11728 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-03-01 16:35:38,183 ERROR   MainThread:11728 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "d:\RLRL\.venv\lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
  File "d:\RLRL\.venv\lib\site-packages\wandb\sdk\wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-03-01 16:35:38,192 WARNING MsgRouterThr:11728 [router.py:message_loop():75] message_loop has been closed
